New model w cablemount
code-iai/iai_pr2 pull request #5
Opened 2023-05-24 09:31 UTC by J-Schaefer

Added new model to update it to the current real robot in the IAI lab. The model also has the cable guide now that is made of item profiles. Also added some new launch files for the sim and the real robot.

2023-05-25 09:31 UTC, J-Schaefer commented
I  tested the new launch file with the real robot instead of `/etc/ros/indigo/robot.launch`. I tried moving the robot with the interactive markers and also ran the demo. Collision avoidance also seems to work fine.

2023-05-25 09:43 UTC, ichumuh requested changes

2023-05-25 09:45 UTC, ichumuh commented
giskard seems to be happy with it though

2023-05-25 09:49 UTC, J-Schaefer commented on iai_pr2_description/robots/pr2_with_odom_joints_cableguide.xacro
If nobody does, then yes. I thought it was safer though. But yeah, no need to keep that much deprecated stuff.

2023-05-25 09:52 UTC, J-Schaefer commented on iai_pr2_description/robots/pr2_calibrated_with_ft2_cableguide.xml
1. Was just easier to integrate (this was also how the FT sensor was added). But true. Will change. 
2. URDF is just the file ending right? Or is there a technical difference? But yes, will change when doing a smaller model.
3. Does this matter? It's very simple meshes. Or are boxer still less computational intense?

2023-05-25 09:52 UTC, J-Schaefer commented on iai_pr2_description/launch/upload_pr2_cableguide.launch
What do you mean? The launch file does include the new URDF or XML in this case. Or do you mean after changing it?

2023-05-25 09:58 UTC, ichumuh commented on iai_pr2_description/robots/pr2_calibrated_with_ft2_cableguide.xml
2. it's fine to combine it, but then we should include it in the old file, or remove the old file. I just don't want multiple urdfs. The ft and ft2 versions also suck. I vote for deleting the ft version to avoid confusion.
3. it doesn't make a huge difference for giskard, but boxes are more efficient than simple meshes. There is no point in adding extra stl files for collision avoidance that is worse.

2023-05-26 08:45 UTC, J-Schaefer commented on iai_pr2_description/robots/pr2_calibrated_with_ft2_cableguide.xml
Added new model now that depends on the original `pr2_calibrated_with_ft2.xml`. It's an `*.xacro` like the other models, though. I also removed the stls and added simple boxes.

2023-05-26 13:36 UTC, J-Schaefer commented on iai_pr2_description/robots/pr2_with_odom_joints_cableguide.xacro
The odom version will for now not be deleted since the simulations in iai_pr2_sim are dependent on it. We can delete it in the future since probably nobody uses this simulation anymore.

2023-05-26 13:38 UTC, J-Schaefer commented on iai_pr2_description/launch/upload_pr2_cableguide.launch
What *display.launch* do you mean? Is this resolved?

2023-05-26 13:39 UTC, J-Schaefer commented
I noticed that the PR2 is still crashing with the camera into the pole. I already added a new collision mesh for the Kinect 1, since it didn't have one. Also need to add a collision (and visual) mesh for the Kinect 2.

2023-06-02 13:51 UTC, J-Schaefer commented
Added Kinect 2 to the model.

2024-02-23 10:58 UTC, ichumuh requested changes

2024-02-23 10:58 UTC, ichumuh commented on iai_pr2_description/launch/upload_pr2_cableguide.launch
I meant `roslaunch iai_pr2_description display.launch`

2024-02-23 10:58 UTC, ichumuh commented
I can also just push it if you want.
Otherwise giskard is happy with the new urdf.

2024-02-23 14:20 UTC, merged